[package]
name = "koyomi"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "koyomi"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.101"
chrono.workspace = true
clap = { version = "4.5.58", features = ["derive"] }
koyomi-core.workspace = true
open = "5.3.3"
serde_json.workspace = true
koyomi-ui.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing.workspace = true
tracing-subscriber = "0.3.22"
